name: Convert TODO to issue
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v4.13.3"
        id: "todo"
